name: Devolution
version: 1.2
author: dado997
main: it.dado997.Devolution.Main
description: A minigame like the real Devolution minigame in the MinePlex server!

commands:
  devolution:
    description: The main command of the Devolution plugin.
    aliases: [dev, DEVOLUTION, DEV]
  devolutionadmin:
    description: The command for setup arenas of the Devolution plugin.
    aliases: [devadmin, DEVOLUTIONADMIN, DevolutionAdmin, dadmin]
  devolutionadmin setarenabounds:
    description: Sets the boundaries of the arena based on your WorldEdit selection or your p1 and p2 positions.